trigger:
  branches:
    include:
      - main  # Replace with your branch name

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    # Add build steps here

- stage: Dev
  dependsOn: Build
  jobs:
  - job: DevJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    # Add steps for deploying to Dev environment

- stage: QA
  dependsOn: Dev
  jobs:
  - job: QAJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    # Add steps for deploying to QA environment

- stage: Production
  dependsOn: QA
  jobs:
  - job: ProductionJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    # Add steps for deploying to Production environment
